import pyttsx3, os

engine = pyttsx3.init()
os.makedirs("data/ai", exist_ok=True)

texts = [
    "Hello this is an AI generated voice sample",
    "Your verification is pending",
    "Please confirm your identity",
    "This is an automated system call",
    "Kindly share the OTP to proceed",
    "Your account is temporarily blocked",
    "Click the link to update details",
    "This message is generated by AI",
    "Verification required within twenty four hours",
    "Failure to respond may suspend access",
    "Mujhe aapka OTP receive nahi hua, please dobara message bhej dijiye so that I can verify the account",
    "Please do not share your bank details or OTP with anyone calling from an unknown number",
    "Please follow the instructions carefully to continue",
    "Your request is being processed by an automated service",
    "Do not ignore this important verification message",
    "System alert generated for unusual account activity",
    "Authentication is necessary before further access",
    "This is a computer generated voice response",
    "Security confirmation is pending for your profile",
    "Please complete the verification within the given time",
    "Immediate action is required to keep your account active",
    "This automated message confirms that your request has been securely received and logged for further processing by the verification system.",
    "Please remain on the line while the system completes a short identity validation procedure designed to protect your digital information.",
    "Your interaction is being monitored by an intelligent security framework to ensure safe and authenticated communication at all times.",
    "This synthesized speech sample is generated for controlled experimentation in artificial intelligence based voice authentication research.",
    "Kindly review the provided instructions carefully before proceeding to the next automated verification step in this secure workflow.",
    "Unusual behavioral activity has been detected in the monitored environment, and precautionary validation is currently recommended.",
    "This notification is part of a structured simulation used to evaluate the reliability of machine learning driven fraud detection systems.",
    "All communication within this session is processed through encrypted automated channels to maintain confidentiality and data protection.",
    "The intelligent assistant is currently analyzing acoustic patterns to determine the authenticity of the incoming speech signal.",
    "Your cooperation with this automated verification routine helps maintain uninterrupted and secure access to essential services.",
    "Artificial speech synthesis engines often produce consistent tonal stability which can be measured through spectral analysis techniques.",
    "The verification workflow is progressing normally and no abnormal interruption has been identified during system level monitoring.",
    "Please ensure that the confirmation sequence is completed within the allocated duration to avoid temporary access limitations.",
    "This generated voice sample demonstrates uniform pronunciation and reduced emotional fluctuation typical of synthetic narration.",
    "Continuous security observation is active to detect any anomaly that may indicate fraudulent or unauthorized interaction behavior.",
    "The automated framework utilizes predictive modeling to classify whether a speech signal originates from a human or artificial source.",
    "System generated reminders are periodically delivered to maintain awareness of pending authentication or verification requirements.",
    "This controlled audio output is intentionally designed with balanced pitch and rhythm for experimental evaluation purposes.",
    "Future communication platforms may rely heavily on automated conversational agents supported by intelligent detection safeguards.",
    "Acoustic fingerprinting techniques enable modern systems to distinguish subtle differences between organic and synthesized voices.",
    "Your digital session integrity remains intact under the supervision of adaptive artificial intelligence monitoring mechanisms.",
    "This procedural narration is included to simulate realistic automated announcements within secure technological environments.",
    "Verification protocols are executed sequentially to maintain structured and reliable interaction across automated communication layers.",
    "Advanced generative audio technologies require equally advanced detection algorithms to preserve trust in voice-based communication.",
    "This message illustrates how artificial systems can replicate fluent speech while still exhibiting measurable synthetic signatures.",
    "Security driven artificial intelligence models continuously evolve to counter emerging threats associated with deepfake audio misuse.",
    "The monitoring engine is calibrated to observe micro-level timing variations that differentiate natural speech from generated output.",
    "All detected parameters are processed through classification pipelines to estimate authenticity confidence in real time.",
    "This synthesized communication concludes the demonstration of automated speech behavior within a protected testing scenario.",
    "End of generated voice sequence. The system has completed this artificial audio evaluation cycle successfully.",

]

for i, text in enumerate(texts):
    engine.save_to_file(text, f"data/ai/ai_{i}.wav")

engine.runAndWait()
print("AI audio files created in data/ai/")
